from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Sequence

import numpy as np
import torch

from utils.ply import read_ply_points

#: Extensions ``load_points`` understands. ``.pth``/``.pt`` hold a raw tensor, not a state dict.
_TORCH_SUFFIXES = (".pth", ".pt")


def cube_pc(center: Sequence[float], num_pts: int, scale: Sequence[float]) -> torch.Tensor:
    """``num_pts`` points drawn uniformly from the axis-aligned box ``center +- scale``.

    Draws x, then y, then z as three separate ``np.random.uniform`` calls. That ordering is part of
    the initialisation: interleaving them, or drawing one ``(num_pts, 3)`` block, produces a
    different point set from the same seed.
    """
    xs = np.random.uniform(-scale[0], scale[0], num_pts) + center[0]
    ys = np.random.uniform(-scale[1], scale[1], num_pts) + center[1]
    zs = np.random.uniform(-scale[2], scale[2], num_pts) + center[2]
    points = np.stack([np.array(xs), np.array(ys), np.array(zs)], axis=-1)
    return torch.from_numpy(points).float()


def cube_normal_pc(center: Sequence[float], num_pts: int, scale: Sequence[float]) -> torch.Tensor:
    """A regular lattice inside ``center +- scale``, topped up to ``num_pts`` with random points.

    PRESERVED BEHAVIOUR (two quirks, both load-bearing for checkpoint reproduction):

    1. ``int(num_pts ** (1/3))`` is a float cube root, so a perfect cube can round *down*: at
       ``num_pts=1000`` it gives ``9`` (``1000 ** (1/3) == 9.999999999999998``), yielding a 9x9x9
       lattice plus 271 random points rather than a clean 10x10x10 lattice. The shipped configs use
       ``init_num: 10000`` -> a 21x21x21 lattice (9261) plus 739 random points.
    2. The remainder is generated by :func:`cube_pc`, which returns ``float32``, and is then
       concatenated with the ``float64`` lattice. The random points are therefore rounded to
       ``float32``, promoted back to ``float64``, and rounded to ``float32`` again by the final
       cast. Building the remainder in ``float64`` instead would change their low bits.
    """
    axis_num_pts = int(num_pts ** (1.0 / 3.0))
    xs = np.linspace(-scale[0], scale[0], axis_num_pts) + center[0]
    ys = np.linspace(-scale[1], scale[1], axis_num_pts) + center[1]
    zs = np.linspace(-scale[2], scale[2], axis_num_pts) + center[2]
    points = np.array([[i, j, k] for i in xs for j in ys for k in zs])
    rest_num_pts = num_pts - points.shape[0]
    if rest_num_pts > 0:
        rest_points = cube_pc(center, rest_num_pts, scale)
        points = np.concatenate([points, rest_points], axis=0)
    return torch.from_numpy(points).float()


def load_points(path: str | Path) -> torch.Tensor:
    """Load an initial cloud as an ``(N, 3)`` ``float32`` CPU tensor.

    ``.ply`` goes through :func:`utils.ply.read_ply_points`, which returns the same ``float64``
    array ``open3d.io.read_point_cloud`` produces, so the subsequent ``float32`` cast lands on
    identical bits. ``.pth``/``.pt`` files hold a bare tensor, loaded with ``weights_only=True``.
    """
    path = Path(path)
    suffix = path.suffix.lower()
    if suffix in _TORCH_SUFFIXES:
        loaded = torch.load(path, map_location="cpu", weights_only=True)
        points = np.asarray(loaded).astype(np.float32)
    elif suffix == ".ply":
        points = read_ply_points(path).astype(np.float32)
    else:
        raise ValueError(f"Unsupported initial point cloud format: {path.suffix.lstrip('.')}")
    return torch.from_numpy(points)


@dataclass(frozen=True)
class InitialPoints:
    """The initial cloud plus the provenance the model needs downstream."""

    points: torch.Tensor
    #: Set only on the loaded path. The model stores this as ``self.gt_points``; it is the
    #: reference cloud the point-to-surface losses compare against.
    gt_points: torch.Tensor | None
    #: ``True`` when ``load_path`` was set and read successfully.
    loaded: bool
    #: Computed in both branches below. It is dead after the init block -- kept so the
    #: correspondence is auditable, not because anything reads it.
    center: Any


def initial_points(
    point_opt: Any,
    *,
    coord_scale: float,
    max_num_pts: int,
    verbose: bool = True,
) -> InitialPoints:
    """Build the initial point cloud from ``geoms.points``, reproducing the archived RNG order.

    ``point_opt`` is the ``geoms.points`` config node. Reads ``load_path``,
    ``prune_outside_bkg_sphere``, ``bkg_sphere_center``, ``bkg_sphere_radius``, ``init_type``,
    ``init_num``, ``init_center`` and ``init_scale``.

    An unreadable ``load_path`` raises. See the ``DEVIATION`` comment below for why that is not a
    preserved-numerics decision.
    """
    load_path = getattr(point_opt, "load_path", "") or ""
    points: torch.Tensor | None = None
    if load_path:
        try:
            points = load_points(load_path)
        except Exception as error:
            raise RuntimeError(
                f"geoms.points.load_path = {load_path!r} could not be read ({error}). This "
                f"release refuses rather than silently training on an empty point cloud. Check "
                f"the path, or clear load_path to use '{point_opt.init_type}' initialisation."
            ) from error
        if points.shape[0] == 0:
            raise RuntimeError(
                f"geoms.points.load_path = {load_path!r} contains no points. Training from an "
                f"empty cloud silently produces a degenerate model."
            )
        if verbose:
            print(f"Loaded points from {load_path}, shape: {tuple(points.shape)}, "
                  f"dtype {points.dtype}")
            _print_extent("Loaded points scale: ", points)

    if points is not None:
        points = _prune_outside_bkg_sphere(points, point_opt, verbose=verbose)
        perm = torch.randperm(points.shape[0])
        selected_indices = perm[:max_num_pts]
        points = points[selected_indices, :].float()
        points = points * coord_scale
        return InitialPoints(points, gt_points=points, loaded=True, center=points.mean(dim=0))

    init_center = [i * coord_scale for i in point_opt.init_center]
    init_scale = [i * coord_scale for i in point_opt.init_scale]
    if point_opt.init_type != "cube":
        raise NotImplementedError(
            f"Point init type [{point_opt.init_type}] is not available in this release; only "
            f"'cube' is reachable from the shipped configs ('sphere' and 'cube_uniform' are not "
            f"implemented)."
        )
    points = cube_normal_pc(init_center, point_opt.init_num, init_scale)
    if verbose:
        _print_extent("Initialized points scale: ", points)
    return InitialPoints(points, gt_points=None, loaded=False, center=init_center)


def _prune_outside_bkg_sphere(
    points: torch.Tensor, point_opt: Any, *, verbose: bool
) -> torch.Tensor:
    """Drop points outside the background sphere, in *canonical* (pre-``coord_scale``) space.

    The radius and centre are stored unscaled in the config and the loaded cloud has not been
    scaled yet at this point, so no ``coord_scale`` factor appears here. ``false`` in all shipped
    configs.
    """
    if not getattr(point_opt, "prune_outside_bkg_sphere", False):
        return points
    center = torch.tensor(getattr(point_opt, "bkg_sphere_center", [0.0, 0.0, 0.0]),
                          dtype=points.dtype)
    radius = getattr(point_opt, "bkg_sphere_radius", 5.0)
    inside = torch.norm(points - center, dim=1) <= radius
    num_before = points.shape[0]
    points = points[inside]
    if verbose:
        print(f"Pruned points outside bkg sphere (radius={radius:.3f}, center={center.tolist()}): "
              f"{num_before} -> {points.shape[0]} ({num_before - points.shape[0]} removed)")
    return points


def _print_extent(prefix: str, points: torch.Tensor) -> None:
    """Log the per-axis extent, a sanity check that coord_scale was applied."""
    extents = ", ".join(
        f"{points[:, axis].min().item():.4f}/{points[:, axis].max().item():.4f}"
        for axis in range(3)
    )
    print(f"{prefix}{extents}")
